# Generated by Django 3.0.7 on 2023-03-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='city',
            new_name='parent',
        ),
    ]
