# Generated by Django 3.0.7 on 2023-03-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20230320_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area',
            new_name='title',
        ),
    ]
