# Generated by Django 3.0.7 on 2023-03-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230308_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='mission',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='setting',
            name='vission',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
