# Generated by Django 3.0.7 on 2023-03-28 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_volunteers'),
        ('home', '0004_contactmessage_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
            preserve_default=False,
        ),
    ]
