# Generated by Django 3.2.18 on 2023-04-09 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0007_volunteers'),
        ('home', '0006_faq_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('head', models.CharField(default='Feedback', max_length=50)),
                ('desc', models.TextField()),
                ('type', models.CharField(default='Website', max_length=7)),
                ('ftime', models.DateTimeField(auto_now_add=True)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
