# Generated by Django 3.2.18 on 2023-04-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_feedback_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='uid',
            field=models.BigIntegerField(null=True),
        ),
    ]
